### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by MiqueiasDevGames** [Calinou/godot-lod#10]
In spatial Lod, if I set max distance of lod0=100, lod1=0, and lod2=0 and use lod0 on the children, I make my children disappear when I pass that distance, that's also useful, right?

But I'm encountering a problem, even close, just turning the camera to the side a little add the meshinstance when I use lod0=50

**Comment by Calinou** [comment]
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

Remember that if you have a mesh for LOD 2, LOD 2 should always have a greater Max Distance than LOD 1. The same applies with LOD 0, which should always have a lower Max Distance than LOD 1.

In short, Max Distances should be: LOD 0 < LOD 1 < LOD 2

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
